# Python Web App to Linux on Azure
# Build a Python WebApp and deploy it to Azure as a Linux WebApp.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - master

name: Build and deploy Python app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master

    # Azure login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_4f3604aa }}
    - uses: azure/appservice-settings@v1
      with:
        app-name: aatiwarishub-python-linux
        app-settings-json: '[{ "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true" }]'
    # Azure logout
    - name: logout
      run: |
        az logout
