# Python Web App to Linux on Azure
# Build a Python WebApp and deploy it to Azure as a Linux WebApp.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - master

name: Build and deploy Python app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master

    # Azure login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_4f3604aa }}
    - run: az webapp config appsettings list --name aatiwarishub-python-linux --resource-group aatiwarishub-rg --query "[?name == 'SCM_DO_BUILD_DURING_DEPLOYMENT'].value"
    - run: echo ::set-output name=scm_do_build::$( az webapp config appsettings list --name aatiwarishub-python-linux --resource-group aatiwarishub-rg --query "[?name == 'SCM_DO_BUILD_DURING_DEPLOYMENT'].value")
    - uses: azure/appservice-settings@v1
      with:
        app-name: aatiwarishub-python-linux
        general-settings-json: '{"linuxFxVersion": "PYTHON|3.7"}' #'General configuration settings as Key Value pairs'
        app-settings-json: '[{ "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true" }]'
    - run: echo " values of scm do build is ${scm_do_build}"
    # Azure logout
    - name: logout
      run: |
        az logout
